[package]
name = "amplitrude-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.81"
bytes = "1.7.1"
clap = { version = "4.5.16", features = ["derive"] }
env_logger = "0.11.5"
itertools = "0.13.0"
pingora = "0.3.0"
pingora-core = "0.3.0"
pingora-http = "0.3.0"
pingora-proxy = "0.3.0"
regex = "1.10.6"
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
serde_yaml = "0.9.34"
url = "2.5.2"
